[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio

; Compilações futuras (quando chegar a tela)
; lib_deps =
;     zinggjm/GxEPD2
;     olikraus/U8g2
;     bblanchon/ArduinoJson

build_flags = 
    -Os

[env:esp32dev_debug]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_type = debug
build_flags = 
    -DDEBUG
    -DCORE_DEBUG_LEVEL=5
